name: CI/CD Pipeline

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."
        
      

  test:
    runs-on: ubuntu-latest
    needs: [build] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: echo "Testing..."

  deploy:
    runs-on: ubuntu-latest

    needs: [test] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        if: github.event_name == push # Chỉ chạy khi được kích hoạt thủ công
        run: |
          echo "Deploying..."
