name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        id: test_job
        run: |
          # Replace with your actual test commands
          echo "Testing..."
          # Assuming some condition determines if deployment should proceed
          echo "CONTINUE_JOBS=true" >> $GITHUB_ENV
          echo "::set-output name=CONTINUE_JOBS::true"

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ needs.test.outputs.CONTINUE_JOBS == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          echo "Deploying..."

