name: CI/CD Pipeline

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: echo "Testing..."

      - name: Set deployment flag
        id: set_deploy_flag
        run: echo "Deploy if needed"  # Thực hiện các công việc kiểm tra hoặc setup cần thiết

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Chỉ chạy bước deploy khi bước test đã hoàn thành thành công

   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying..."
