name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello World"
      - name: Check Version Node
        run: |
          echo "Node.js version:"
          node --version
       
