name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        CONTINUE_JOBS: ${{ steps.manual-trigger.outputs.CONTINUE_JOBS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."
  test:
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
        CONTINUE_JOB: ${{ steps.test.outputs.CONTINUE_JOBS == 'true' }} //test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."
    
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          echo "Deploying..."
 

 
